# Generated by Django 5.1.2 on 2024-11-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservatiom',
            new_name='Reservation',
        ),
    ]
