# Generated by Django 5.1.2 on 2024-11-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_reservatiom_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
